resolver: lts-16.4
packages:
- '.'
extra-deps:
- binary-instances-1.0.0.1
- extensible-0.8
- fallible-0.1.0
- github-0.26
- membership-0
- github: matsubara0507/mix.hs
  commit: a0b2b9394c340186c9a8a63808f0db1752ada4ae
  subdirs:
  - mix
  - mix-plugin-github

docker:
  repo: matsubara0507/stack-build
  enable: false
