resolver: lts-16.31
packages:
- '.'
extra-deps:
- binary-instances-1.0.0.1
- extensible-0.8.1
- fallible-0.1.0
- github-0.26
- incremental-0.3.1
- membership-0
- github: matsubara0507/mix.hs
  commit: 75714be080db16f6a4f9d0a22e86947ffcdadc57
  subdirs:
  - mix
  - mix-plugin-github

docker:
  repo: matsubara0507/stack-build
  enable: false
